version: "3"

services:
  web:
    image: misskey/misskey:${SOFTWARE_VERSION_TAG}
    restart: always
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    ports:
      - "172.17.0.1:26612:3000"
    # networks:
    #   - internal_network
    #   - external_network
    volumes:
      - ./storage/files:/misskey/files
      - ./storage/misskey/.config:/misskey/.config:ro

  redis:
    restart: always
    image: elestio/redis:7.0
    # networks:
    #   - internal_network
    volumes:
      - ./storage/redis:/data

  db:
    restart: always
    image: elestio/postgres:15
    # networks:
    #   - internal_network
    env_file:
      - ./.env
    volumes:
      - ./storage/db:/var/lib/postgresql/data
    ports:
      - 172.17.0.1:8073:5432
  # networks:
  #   internal_network:
  #     internal: true
  #   external_network:

  pgadmin:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "172.17.0.1:49343:8080"
    volumes:
      - ./storage/servers.json:/pgadmin4/servers.json
